import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

// Simple service worker registration for PWA functionality
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    // In a real build step, this would point to sw.js generated by Vite/Webpack
    // For this generated code block, we just log that we would register it.
    // To make this fully offline capable, a sw.js file handling caching is needed.
    // For now, the structure supports the concept.
    console.log('Service Worker registration supported');
  });
}

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error("Could not find root element to mount to");
}

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
